name: Android CI

on: push

jobs:
  build:
    name: Development build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
    
      - name: Restore gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Restore SonarCloud packages cache
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Manually install latest build tools (takes up to two weeks to update in action images)
      - name: Install latest build tools
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "build-tools;30.0.3" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Build with Gradle
        #      env:
        #        key: value
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: AdAway-dev
          path: app/build/outputs/apk/release/app-release-unsigned.apk
