name: Android CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Development build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .gradle
        run: mkdir -p ~/.gradle

      - name: Create gradle.properties
        run: |
          echo "signingStoreLocation=$GITHUB_WORKSPACE/key.store
          signingStorePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
          signingKeyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
          signingKeyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" > ~/.gradle/gradle.properties

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Restore SonarCloud packages cache
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - run: sed -i 's% ANDROID_SYSTEM_ETC_HOSTS .*% ANDROID_SYSTEM_ETC_HOSTS = "/storage/emulated/0/hosts";%g' app/src/main/java/org/adaway/util/Constants.java

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace

      # - name: Upload APK
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: AdAway-dev
      #     path: app/build/outputs/apk/release/app-release-unsigned.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AdAway-dev
          path: app/build/outputs/apk/release/*.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: vlatest
          files: app/build/outputs/apk/release/*.apk

      - name: Update dependency graph
        uses: mikepenz/gradle-dependency-submission@v0.8.5 # Deprecated: need to be changed
        with:
          gradle-dependency-path: "app/build.gradle"
          gradle-build-module: ":app"
          gradle-build-configuration: "releaseCompileClasspath"

      - name: Analyze project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m sonarqube
